### ISSUE TITLE
react-gantt breaking changes when upgrading from 18.4.43 to 19.1.66

### ISSUE THREAD

**Issue by dnohashi** [syncfusion/ej2-react-ui-components#84]
Upgrading @syncfusion/ej2-react-gantt from 18.4.43 to 19.1.66 resulted in the following error - 
  1. Applying a `template={}` prop to customize the column content is resulting in
     a. str.match is not a function
     b. Cannot read property 'destroy' of undefined
     c. Cannot read property 'close' of undefined

I don't see any upgrade instructions/potential breaking changes documented on the CHANGELOG.md

Is this a known issue? This ColumnDirective was working prior to the upgrade. Please advise. Thanks :)

**Comment by dnohashi** [comment]
If I remove the template, I do not experience any rendering issues; however, it appears filtering no longer works. I receive the following error:
<img width="705" alt="Screen Shot 2021-06-03 at 2 47 30 PM" src="https://user-images.githubusercontent.com/21189697/120716461-eca19a00-c47a-11eb-89dd-213784f6b0f7.png">

**Comment by MonishaSivanthilingam** [comment]
Hi dnohashi,

Greetings from Syncfusion support.

We have analyzed your issue, however, we were unable to replicate the issue you reported about not being able to use column template after migrating to version v19.1.66. We also checked with filtering, and we were able to perform filtering actions with/without the use of column template. Please share more details about the issue you faced, such as:

1.	In what cases are you facing the issue you reported ?
2.	Are you not able to render the Gantt at all or is it only the contents of the column you used column template on ?
3.	What kind of customizations are you performing in the column using the column template ?
4.	Please share a screenshot of the script error thrown.
5.	We have attached the sample we used to validate your issue. If possible, please modify it to replicate your issue or please share an issue reproducible sample of your own.

**Sample:** https://stackblitz.com/edit/react-7orkff

Any information you could share with us will be useful to us in providing you with a solution.

Regards,
Monisha.
